[database]
database_url = "postgresql://postgres:postpass@db:5432/postgres"
use_local_database = true
local_database_url = "sqlite:///database.db"

[docs]
title = "API"
version = "1.0.0"
description = """
# A API
"""
